config/routes.rb
Rails.application.routes.draw do

  resources :lessons do
    collection do
      post 'new_lesson'
      post 'review'
    end
  end
  
  resources :schedules do
    collection do
      get 'get_schedules'
      post 'save_schedule'
      post 'aprovar'
      post 'reject'
      post 'cancel'
      get 'activities'
    end
  end
    
  resources :type_reservations do
    collection do
      post 'novo_tipo'
      post 'atualizar_tipo'
    end
  end

  resources :equipaments do
    collection do
      get 'equipaments_labs'
      get 'equipaments_labs_json'
      post 'toggle_eqp'
    end
  end
  
  resources :laboratorys do
    collection do
      post 'new_laboratory'
      post 'edit_laboratory'
      get 'get_laboratory'  
      post 'toggle_lab'
    end
  end
  
  resources :disciplinas do
    collection do
      get 'find_professor'
      post 'nova_disciplina'
      get 'get_disciplina' 
      post 'atualizar_disciplina'     
      post 'toggle'
    end
  end

  resources :escolas do
    collection do
      get 'nova_escola'
      get 'atualizar_escola'
    end
  end

  root to: 'welcome#index'
  get 'welcome/index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }
  resources :roles
  resources :users do
    member do
      get 'toggle_user'
    end
    collection do
      post 'alter_permission'
      post 'alter_password'
    end
  end

  resources :upload do
    collection do
      get 'download_file'
      get 'remove_file'
    end
  end
  
  mount ExceptionLogger::Engine => "/exception_logger"
end

app/models/anexo.rb
class Anexo < ApplicationRecord

  mount_uploader :file, AnexosUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
  belongs_to :professor, class_name: 'User'
  belongs_to :escola
  has_many :anexos, foreign_key: 'anexo_id'

  validates :nome, :professor_id, :escola_id, presence: true
end

app/models/equipament.rb
class Equipament < ApplicationRecord
  belongs_to :laboratory
  has_many :anexos, foreign_key: 'anexo_id'

  mount_uploader :image, ImageEquipamentsUploader
  
end

app/models/escola.rb
class Escola < ApplicationRecord
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  belongs_to :escola
  has_many :schedules
  has_many :anexos, foreign_key: 'anexo_id'

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :laboratory
  belongs_to :disciplina
  has_many :anexos, foreign_key: 'anexo_id'
  
  #mount_uploader :solicitacao_aula, SolicitacaoAulaUploader

  def self.week_day(day)
    case day
    when 'dom'
      return 0
    when 'seg'
      return 1
    when 'ter'
      return 2
    when 'qua'
      return 3
    when 'qui'
      return 4
    when 'sex'
      return 5
    when 'sab'
      return 6
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  include PublicActivity::Model

  belongs_to :equipament, optional: true
  belongs_to :laboratory
  belongs_to :user
  belongs_to :type_reservation

  def self.criarAgendamento(inicio, fim, lab, userId, lessonId)
    ax = Schedule.new(start: inicio, end: fim, type_reservation_id: 1, laboratory_id: lab, user_id: userId, status: 'CONFIRMADO', lesson_id: lessonId )
    ax.save
  end
end

app/models/type_reservation.rb
class TypeReservation < ApplicationRecord
    has_many :schedules
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role, optional: true
  belongs_to :escola, optional: true
  has_many :schedules
  
  validates :email, uniqueness: true
  validates :nome, :celular, presence: true
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

  def human_date(date)
    return date.strftime("%d/%m/%Y") unless date.nil?
  end

  def human_datetime(date)
    return date.strftime("%d/%m/%Y %H:%M:%S") unless date.nil?
  end

  def human_time(time)
    return time.strftime("%H:%M") unless time.nil?
  end

  def human_boolean(boolean)
    return boolean ? 'Sim' : 'Não'
  end

end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/helpers/escolas_helper.rb
module EscolasHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def week_day(day)
    case day
    when 'dom'
      return 0
    when 'seg'
      return 1
    when 'ter'
      return 2
    when 'qua'
      return 3
    when 'qui'
      return 4
    when 'sex'
      return 5
    when 'sab'
      return 6
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/shared/_messages.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a href="#" class="nav-link dropdown-toggle" id="messagesDropdown" 
    role="button" data-toggle="dropdown" aria-haspopup="true" 
    aria-expanded="false">
    <i class="fas fa-envelope fa-fw"></i>

    <!-- Counter - Messages -->
    <% if @messages.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @messages.size %>
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Messages -->
  <div aria-labelledby="messagesDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Message Center
    </h6>

    <% @messages&.each do |message| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="dropdown-list-image mr-3">
        <img class="rounded-circle" src="<%= message.sender_avatar %>" alt="">
        <div class="status-indicator bg-success"></div>
      </div>
      <div class="font-weight-bold">
        <div class="text-truncate"><%= message.content %></div>
        <div class="small text-gray-500"><%= message.sender %></div>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Read More Messages
    </a>
  </div>
</li>

app/views/layouts/shared/_notifications.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" 
    role="button" data-toggle="dropdown"aria-haspopup="true"
    aria-expanded="false">
    <i class="fas fa-bell fa-fw"></i>

    <!-- Counter - Alerts -->
    <% if @notifications.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @notifications.size %>+
      </span>
    <% end %>
  </a>

  <!-- Dropdown - Alerts -->
  <div aria-labelledby="alertsDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right 
           shadow animated--grow-in">

    <h6 class="dropdown-header">
      Alerts Center
    </h6>

    <% @notifications&.each do |notification| %>
    <a class="dropdown-item d-flex align-items-center" href="#">
      <div class="mr-3">
        <div class="icon-circle bg-<%= notification.kind %>">
          <i class="fas fa-file-alt text-white"></i>
        </div>
      </div>
      <div>
        <div class="small text-gray-500"><%= notification.date %></div>
        <% if notification.viewed %>
          <%= notification.content %>
        <% else %>
          <span class="font-weight-bold"><%= notification.content %></span>
        <% end %>
      </div>
    </a>
    <% end %>

    <a class="dropdown-item text-center small text-gray-500" href="#">
      Show All Alerts
    </a>
  </div>
</li>

app/views/layouts/shared/_search_dropdown.html.erb
<li class="nav-item dropdown no-arrow d-sm-none">
  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-search fa-fw"></i>
  </a>
  <!-- Dropdown - Messages -->
  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
    <form class="form-inline mr-auto w-100 navbar-search">
      <%= render "layouts/shared/search_field" %>
    </form>
  </div>
</li>

app/views/layouts/shared/_search_field.html.erb
<div class="input-group">
  <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-primary" type="button">
      <i class="fas fa-search fa-sm"></i>
    </button>
  </div>
</div>

app/views/layouts/shared/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
    <div class="sidebar-brand-icon rotate-15">
      <i class="fas fa-vials"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SARLAB</div>
  </a>

      <!-- Divider -->
  <%# <hr class="sidebar-divider my-0">

  <% if current_user.role_id.eql? 1 
      <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="fas fa-fw fa-tachometer-alt"></i><span>Dashboard</span>
      </a>
    </li>
  <% end %> 

      <!-- Divider -->
  <hr class="sidebar-divider">
  
  <li class="nav-item">
    <%= link_to schedules_path, :class => "nav-link" do %>
      <i class="fas fa-fw fa-calendar"></i> <span>Agenda</span>
    <% end %>
  </li>

  <hr class="sidebar-divider">

  <% unless current_user.role_id.eql? 3 %>
      <!-- Heading -->
    <div class="sidebar-heading">
      Cadastros
    </div>
    <% if current_user.role_id.eql? 1 %>
      <li class="nav-item">
        <%= link_to escolas_path, :class => "nav-link" do %>
          <i class="fas fa-fw fa-school"></i> <span>Escolas</span>
        <% end %>
      </li>
    <% end %>
    <li class="nav-item">
      <%= link_to disciplinas_path, :class => "nav-link" do %>
        <i class="fas fa-fw fa-book"></i> <span>Disciplinas</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to lessons_path, :class => "nav-link" do %>
        <i class="fas fa-fw fa-address-book"></i> <span>Aulas</span>
      <% end %>
    </li>
    <% if current_user.role_id.eql? 1 %>
      <li class="nav-item">
        <%= link_to laboratorys_path, :class => "nav-link" do %>
          <i class="fas fa-fw fa-flask"></i> <span>Laboratórios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to equipaments_path, :class => "nav-link" do %>
          <i class="fas fa-fw fa-bookmark"></i> <span>Equipamentos</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to type_reservations_path, :class => "nav-link" do %>
          <i class="fas fa-fw fa-bookmark"></i> <span>Tipos de reservas</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, :class => "nav-link" do %>
          <i class="fas fa-fw fa-users"></i> <span>Usuários</span>
        <% end %>
      </li>
    <% end %>
  <% end %>
  
      <!-- Nav Item - Pages Collapse Menu -->
  <%# <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Components</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Components:</h6>
        <a class="collapse-item" href="buttons.html">Buttons</a>
        <a class="collapse-item" href="cards.html">Cards</a>
      </div>
    </div>
  </li> %>
</ul>

app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <!--<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <%= render "layouts/shared/search_field" %>  
  </form>  -->

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <%= render "layouts/shared/search_dropdown" %>
    <%= render "layouts/shared/notifications" %>
    <%= render "layouts/shared/messages" %>            

    <div class="topbar-divider d-none d-sm-block"></div>

    <%= render "layouts/shared/user_nav" %>
  </ul>

</nav>

app/views/layouts/shared/_user_nav.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.present? ? current_user.nome : 'usuário' %></span>
    <img class="img-profile rounded-circle" src="https://user-images.githubusercontent.com/44842616/104138186-4517b400-5381-11eb-9dfb-050f9d823ddf.png">
  </a>
              <!-- Dropdown - User Information -->
    <ul class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">      
      <li><%= link_to edit_user_path(current_user.id), :class => "dropdown-item" do %>
        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>Perfil
        <% end %>
      </li>
      <li><a class="dropdown-item" id="btn_alter_password">
        <i class="fas fa-lock fa-sm fa-fw mr-2 text-gray-400"></i>Alterar senha</a>
      </li>
      <li><%= link_to destroy_user_session_path, method: :delete, :class => "dropdown-item" do %>
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Sair
        <% end %>
      </li>
    </ul>
</li>

<script>
  $('#btn_alter_password').click(function () {
    $('#modalAlterPassword').modal('show');
  });
</script>