config/routes.rb
Rails.application.routes.draw do

  resources :lessons do
    collection do
      post 'new_lesson'
      post 'review'
    end
  end
  
  resources :schedules do
    collection do
      get 'get_schedules'
      post 'save_schedule'
      post 'aprovar'
      post 'reject'
      post 'cancel'
      get 'activities'
    end
  end
    
  resources :type_reservations do
    collection do
      post 'novo_tipo'
      post 'atualizar_tipo'
    end
  end

  resources :equipaments do
    collection do
      get 'equipaments_labs'
      get 'equipaments_labs_json'
      post 'toggle_eqp'
    end
  end
  
  resources :laboratorys do
    collection do
      post 'new_laboratory'
      post 'edit_laboratory'
      get 'get_laboratory'  
      post 'toggle_lab'
    end
  end
  
  resources :disciplinas do
    collection do
      get 'find_professor'
      post 'nova_disciplina'
      get 'get_disciplina' 
      post 'atualizar_disciplina'     
      post 'toggle'
    end
  end

  resources :escolas do
    collection do
      get 'nova_escola'
      get 'atualizar_escola'
    end
  end

  root to: 'welcome#index'
  get 'welcome/index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }
  resources :roles
  resources :users do
    member do
      get 'toggle_user'
    end
    collection do
      post 'alter_permission'
      post 'alter_password'
    end
  end

  resources :upload do
    collection do
      get 'download_file'
      get 'remove_file'
    end
  end
  
  mount ExceptionLogger::Engine => "/exception_logger"
end

app/models/equipament.rb
class Equipament < ApplicationRecord
  belongs_to :laboratory
  has_many :anexos, foreign_key: 'anexo_id'

  mount_uploader :image, ImageEquipamentsUploader
  
end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_equipament, only: [:show, :edit, :update, :destroy]

  # GET /equipaments
  # GET /equipaments.json
  def index
    @q = Equipament.ransack(params[:q])
    @equipaments = @q.result

    if params[:q] && params[:q]['active'] == 'true'
      @equipaments = @equipaments.where(active: true)
    elsif params[:q] &&  params[:q]['active'] == 'false'
      @equipaments = @equipaments.where(active: false)
    end  
  end

  # GET /equipaments/1
  # GET /equipaments/1.json
  def show
    @anexos = Anexo.where(equipament_id: @equipament.id)
  end

  # GET /equipaments/new
  def new
    @equipament = Equipament.new
  end

  # GET /equipaments/1/edit
  def edit
  end

  # POST /equipaments
  # POST /equipaments.json
  def create
    @equipament = Equipament.new(equipament_params)

    respond_to do |format|
      if @equipament.save
        format.html { redirect_to @equipament, notice: 'Equipamento cadastrado com sucesso' }
        format.json { render :show, status: :created, location: @equipament }
      else
        format.html { render :new }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipaments/1
  # PATCH/PUT /equipaments/1.json
  def update
    respond_to do |format|
      if @equipament.update(equipament_params)
        format.html { redirect_to @equipament, notice: 'Equipamento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @equipament }
      else
        format.html { render :edit }
        format.json { render json: @equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipaments/1
  # DELETE /equipaments/1.json
  def destroy
    @equipament.destroy
    respond_to do |format|
      format.html { redirect_to equipaments_url, notice: 'Equipament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def equipaments_labs
    @equipaments = Equipament.where(laboratory_id: params[:lab])
    render :index
  end

  def equipaments_labs_json
    equipaments = Equipament.where(laboratory_id: params[:lab])
    
    render json: equipaments
  end

  def toggle_eqp
    eqp = Equipament.find params[:id]
    
    eqp.update(active: !eqp.active)

    render json: eqp
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipament
      @equipament = Equipament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipament_params
      params.require(:equipament).permit(:name, :description, :brand, :model, :capacity, :patrimony, :laboratory_id, :simultaneous_use, :image)
    end
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/views/equipaments/_form.html.erb
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body">
    <%= form_with(model: equipament, local: true) do |form| %>
      <% if equipament.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(equipament.errors.count, "error") %> prohibited this equipament from being saved:</h2>

          <ul>
          <% equipament.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row field">
        <%= form.label 'Name', 'Nome', class: 'col-2 control-label padding'  %>
        <div class="col-sm-10">          
          <%= form.text_field :name, class: 'form-control form-control' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :description, 'Descrição', class: 'col-2 control-label padding'  %>
        <div class="col-sm-10">          
          <%= form.text_area :description, rows:2, class: 'form-control form-control' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'brand', 'Marca', class: 'col-2 control-label padding'  %>
        <div class="col-sm-4">          
          <%= form.text_field :brand, class: 'form-control form-control' %>
        </div>

        <%= form.label 'model', 'Modelo', class: 'col-2 control-label padding'  %>
        <div class="col-sm-4">          
          <%= form.text_field :model, class: 'form-control form-control' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'capacity', 'Capacidade', class: 'col-2 control-label padding'  %>
        <div class="col-sm-4">          
          <%= form.text_field :capacity, class: 'form-control form-control' %>
        </div>

        <%= form.label 'patrimony', 'Patrimônio', class: 'col-2 control-label padding'  %>
        <div class="col-sm-4">          
          <%= form.text_field :patrimony, class: 'form-control form-control' %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'simultaneous_use', 'Uso simultâneo', class: 'col-3 control-label'  %>
        <div class="col-sm-3">          
          <%= form.number_field :simultaneous_use, class: 'form-control form-control' %>
        </div>

        <%= form.label 'laboratory_id', 'Laboratório', class: 'col-2 control-label padding' %>
        <div class="col-sm-4"> 
          <%= form.collection_select :laboratory_id, Laboratory.all, :id, :name, { :include_blank => true},
                                                {class: 'form-control input-sm'} %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'image', 'Foto', class: 'col-3 control-label'  %>
        <div class="col-sm-3">          
          <%= form.file_field :image, class: 'form-control form-control' %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/equipaments/edit.html.erb
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="text-left">
            <span class="h1 font-weight text-lg-gray-800 mb-4">Editar Equipamento</span>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'form', equipament: @equipament %>

app/views/equipaments/index.html.erb
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="text-left">
            <span class="h1 font-weight text-lg-gray-800 mb-4">Equipamentos</span>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#FilterEquipament" class="d-block card-header py-3 collapsed" data-toggle="collapse"
        role="button" aria-expanded="false" aria-controls="FilterEquipament" style="background-color: white;">
        <h6 class="m-0 font-weight-bold text-primary">Filtro</h6>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse" id="FilterEquipament">
        <div class="card-body">
          <%= search_form_for @q do |f| %>
            <div class="form-group row">
              <div class="col-sm-6">
                <%= f.label :laboratory_id_eq, 'Laboratório'  %>
                <%= f.collection_select :laboratory_id_eq, Laboratory.all.order(:name), :id, :name, {include_blank: true} %>
              </div>         
              <div class="col-sm-6">
                <%= f.label :name_cont, 'Nome'  %>
                <%= f.text_field :name_cont, class: 'w-80' %>
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-6">
                <%= f.label :active, "Todos", :value => "todos"  %>
                <%= f.radio_button :active, nil, :checked => true %>
                <%= f.label :active, "Ativos", :value => "true", class:"pd-10"  %>
                <%= f.radio_button :active, true %>
                <%= f.label :active, "Desativados", :value => "false", class:"pd-10" %>
                <%= f.radio_button :active, false %>
              </div>
            </div>

            <%= f.submit :class => 'btn btn-primary' %>
          <% end %>
        </div>
    </div>
</div>

<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="d-sm-flex align-items-center mb-4">
            <%# <button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" id="btn_new_lab">
              <i class="fas fa-flask" aria-hidden="true"> Laboratório</i>
            </button> %>
            <%= link_to new_equipament_path, :class => "ml-1 d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
              <i class="fas fa-plus-square"></i>Novo equipamento
            <% end %>
          </div>          
        </div>
      </div>
    </div>

    <div class="row mr-1 ml-1">
      <% @equipaments.each do |eqp| %>
        <div class="col-lg-6">
          <div class="card mb-4" style="heighut:20px;">
            <%# <%= image_tag(eqp.image_url.to_s, class:"card-img-top") %>
              <div class="card-header-nopadding">
                <h5 class="m-0 font-weight-bold text-white"><%= eqp.name %></h5>
              </div>
              <div class="card-body" style="padding:0.5rem !important;">
              <p class="card-text" ><%= eqp.description %></p>
              <hr>  
                <%= link_to 'Exibir', equipament_path(eqp),  class:"btn btn-success btn-sm" %>          
                <%= link_to 'Editar', edit_equipament_path(eqp), :class => 'btn btn-primary btn-sm' %>
                <% if eqp.active %>
                  <button class="btn btn-warning btn-sm" type="button" onclick="toggle_eqp(<%= eqp.id %>)">Desativar</button>
                <% else %>
                  <button class="btn btn-success btn-sm" type="button" onclick="toggle_eqp(<%= eqp.id %>)">Ativar</button>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<style>
  .h-38{ 
    height: 38px !important;
  }
  .w-80{
    width: 80%
  }
  .pd-10{
    padding-left: 10px
  }
</style>

app/views/equipaments/new.html.erb
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="text-left">
            <span class="h1 font-weight text-lg-gray-800 mb-4">Novo Equipamento</span>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'form', equipament: @equipament %>

app/views/equipaments/show.html.erb
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body">
    <div class="form-group row">
      <%= label_tag 'Nome', 'Nome', class: 'col-2 control-label padding'  %>
      <div class="col-sm-10">        
        <%= text_field_tag :name, @equipament.name, class: 'form-control form-control', readOnly: "true" %>
      </div>
    </div>
    <div class="form-group row">
      <%= label_tag 'description', 'Descrição', class: 'col-2 control-label padding'  %>
      <div class="col-sm-10">        
        <%= text_area_tag :description, @equipament.description, rows: 2, class: 'form-control form-control', readOnly: "true" %>
      </div>
    </div>
    <div class="form-group row">
      <%= label_tag 'brand', 'Marca', class: 'col-2 control-label padding'  %>
      <div class="col-sm-4">        
        <%= text_field_tag :brand, @equipament.brand, class: 'form-control form-control', readOnly: "true" %>
      </div>

      <%= label_tag 'model', 'Modelo', class: 'col-2 control-label padding'  %>
      <div class="col-sm-4">        
        <%= text_field_tag :model, @equipament.model, class: 'form-control form-control', readOnly: "true" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-6">
        <div class="form-group row">
          <%= label_tag 'capacity', 'Capacidade', class: 'col-4 control-label padding'  %>
          <div class="col-sm-8">        
            <%= text_field_tag :capacity, @equipament.capacity, class: 'form-control form-control', readOnly: "true" %>
          </div>
        </div>
        <div class="form-group row">
          <%= label_tag 'patrimony', 'Patrimônio', class: 'col-4 control-label padding'  %>
          <div class="col-sm-8">        
            <%= text_field_tag :patrimony, @equipament.patrimony, class: 'form-control form-control', readOnly: "true" %>
          </div>
        </div>
        <div class="form-group row">
          <%= label_tag 'simultaneous_use', 'Uso simultâneo', class: 'col-6 control-label padding'  %>
          <div class="col-sm-6">        
            <%= number_field_tag :simultaneous_use, @equipament.simultaneous_use, class: 'form-control form-control', readOnly: "true" %>
          </div>
        </div>
        <div class="form-group row">
          <%= label_tag 'laboratory', 'Laboratório', class: 'col-4 control-label padding'  %>
          <div class="col-sm-8">        
            <%= text_field_tag :laboratory, @equipament.laboratory.name, class: 'form-control form-control', readOnly: "true" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <%= image_tag(@equipament.image_url.to_s) %>
      </div>   
    </div>
    
    <div class="actions">
      <%= link_to 'Editar', edit_equipament_path(@equipament), :class => 'btn btn-primary' %>
      <%= link_to 'Voltar', equipaments_path, :class => 'btn btn-secondary' %>
    </div>
  </div>
</div>
<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body">
    <div class="row">
      <div class="col-lg-6">
        <form action="/upload" id="mediadropzone" class="dropzone" enctype="multipart/form-data">
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
          <%= hidden_field_tag 'equipament', @equipament.id %>
          <div class="dz-message">    
            Arraste os arquivos ou clique para fazer upload
          </div>
          <div class="fallback">
          <input name="media" type="file" multiple />
          </div>
        </form>
      </div>
      <div class="col-lg-6">
        <h5><i class="fa fa-paperclip"> </i> Anexos</h5>
        <% if @anexos.present? %>
          <div class="col-sm-6">
            <% @anexos.each do |att|%>
              <div id="anexo-<%=att.id%>">
                <i class="fa fa-file-text-o"></i> <%= link_to File.basename(att.file.path), {action: 'download_file', id: att.id, controller: 'upload'}, target: '_blank'  %>
                <button style="font-size: 10px" type="button" class="btn btn-sm btn-danger" onclick="remover_anexo('<%= att.id %>')" ><i class="fa fa-trash"></i> </button>                                                  
                <br />
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>