config/routes.rb
Rails.application.routes.draw do

  resources :lessons do
    collection do
      post 'new_lesson'
      post 'review'
    end
  end
  
  resources :schedules do
    collection do
      get 'get_schedules'
      post 'save_schedule'
      post 'aprovar'
      post 'reject'
      post 'cancel'
      get 'activities'
    end
  end
    
  resources :type_reservations do
    collection do
      post 'novo_tipo'
      post 'atualizar_tipo'
    end
  end

  resources :equipaments do
    collection do
      get 'equipaments_labs'
      get 'equipaments_labs_json'
      post 'toggle_eqp'
    end
  end
  
  resources :laboratorys do
    collection do
      post 'new_laboratory'
      post 'edit_laboratory'
      get 'get_laboratory'  
      post 'toggle_lab'
    end
  end
  
  resources :disciplinas do
    collection do
      get 'find_professor'
      post 'nova_disciplina'
      get 'get_disciplina' 
      post 'atualizar_disciplina'     
      post 'toggle'
    end
  end

  resources :escolas do
    collection do
      get 'nova_escola'
      get 'atualizar_escola'
    end
  end

  root to: 'welcome#index'
  get 'welcome/index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'

  }
  resources :roles
  resources :users do
    member do
      get 'toggle_user'
    end
    collection do
      post 'alter_permission'
      post 'alter_password'
    end
  end

  resources :upload do
    collection do
      get 'download_file'
      get 'remove_file'
    end
  end
  
  mount ExceptionLogger::Engine => "/exception_logger"
end

app/models/escola.rb
class Escola < ApplicationRecord
end

app/controllers/escolas_controller.rb
class EscolasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_escola, only: [:show, :edit, :update, :destroy, :atualizar_escola]

  # GET /escolas
  # GET /escolas.json
  def index
    @escolas = Escola.all
  end

  # GET /escolas/1
  # GET /escolas/1.json
  def show
  end

  # GET /escolas/new
  def new
    @escola = Escola.new
  end

  # GET /escolas/1/edit
  def edit
  end

  # POST /escolas
  # POST /escolas.json
  def create
    @escola = Escola.new(escola_params)

    respond_to do |format|
      if @escola.save
        format.html { redirect_to @escola, notice: 'Escola was successfully created.' }
        format.json { render :show, status: :created, location: @escola }
      else
        format.html { render :new }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escolas/1
  # PATCH/PUT /escolas/1.json
  def update
    respond_to do |format|
      if @escola.update(escola_params)
        format.html { redirect_to @escola, notice: 'Escola was successfully updated.' }
        format.json { render :show, status: :ok, location: @escola }
      else
        format.html { render :edit }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escolas/1
  # DELETE /escolas/1.json
  def destroy
    @escola.destroy
    respond_to do |format|
      format.html { redirect_to escolas_url, notice: 'Escola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def nova_escola
    escola = Escola.new(nome: params[:nome], endereco: params[:endereco], numero: params[:numero], bairro: params[:bairro], 
                        cidade: params[:cidade], responsavel: params[:responsavel], telefone: params[:telefone]);
    escola.save!
    render json: escola
  end

  def atualizar_escola
    @escola.update(nome: params[:nome], endereco: params[:endereco], numero: params[:numero], bairro: params[:bairro], 
                        cidade: params[:cidade], responsavel: params[:responsavel], telefone: params[:telefone]);
    @escola.save!

    render json: @escola
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escola
      @escola = Escola.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def escola_params
      params.require(:escola).permit(:nome, :endereco, :numero, :bairro, :cidade, :responsavel, :telefone)
    end
end

app/helpers/escolas_helper.rb
module EscolasHelper
end

app/views/escolas/_form.html.erb
<%= form_with(model: escola, local: true) do |form| %>
  <% if escola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(escola.errors.count, "error") %> prohibited this escola from being saved:</h2>

      <ul>
      <% escola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :responsavel %>
    <%= form.text_field :responsavel %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/escolas/_modal_edit_escola.html.erb
<div class="modal fade" id="modalEditEscola" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog w-700"]>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" > Escola </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form class="form-horizontal" id="form_edit_escola">
        <div class="modal-body">
          <div class="form-group row">
            <div class="col-sm-12">
              <%= label_tag 'Instituição', nil %>
              <%= text_field_tag :nome, nil, class: 'form-control form-control' %>
              <%= hidden_field_tag 'escola_id', nil, class: 'form-control input-sm' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Endereço', nil %>
              <%= text_field_tag :endereco, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Número', nil %>
              <%= text_field_tag :numero, nil, class: 'form-control form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Bairro', nil %>
              <%= text_field_tag :bairro, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Cidade', nil %>
              <%= text_field_tag :cidade, nil, class: 'form-control form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Responsável', nil %>
              <%= text_field_tag :responsavel, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Telefone', nil %>
              <%= text_field_tag :telefone, nil, class: 'form-control form-control', :id=> 'telefone' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">            
          <%= submit_tag 'Salvar', :id => 'btn_editar_escola', :class => 'btn btn-primary'%>
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
        </div>
      </form>
    </div>
  </div>
</div> 

app/views/escolas/_modal_new_escola.html.erb
<div class="modal fade" id="modalNewEscola" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog w-700"]>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" > Nova escola </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form class="form-horizontal" id="form_escola">
        <div class="modal-body">
          <div class="form-group row">
            <div class="col-sm-12">
              <%= label_tag 'Instituição', nil %>
              <%= text_field_tag :nome, nil, class: 'form-control form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Endereço', nil %>
              <%= text_field_tag :endereco, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Número', nil %>
              <%= text_field_tag :numero, nil, class: 'form-control form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Bairro', nil %>
              <%= text_field_tag :bairro, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Cidade', nil %>
              <%= text_field_tag :cidade, nil, class: 'form-control form-control' %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= label_tag 'Responsável', nil %>
              <%= text_field_tag :responsavel, nil, class: 'form-control form-control' %>
            </div>
            <div class="col-sm-6">
              <%= label_tag 'Telefone', nil %>
              <%= text_field_tag :telefone, nil, class: 'form-control form-control', :id=> 'telefone' %>
            </div>
          </div>
        </div>  
        <div class="modal-footer">            
          <%= submit_tag 'Salvar', :id => 'btn_create_escola', :class => 'btn btn-primary'%>
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
        </div>
      </form>
    </div>
  </div>
</div> 

app/views/escolas/edit.html.erb
<h1>Editing Escola</h1>

<%= render 'form', escola: @escola %>

<%= link_to 'Show', @escola %> |
<%= link_to 'Back', escolas_path %>

app/views/escolas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="text-left">
            <span class="h1 font-weight text-lg-gray-800 mb-4">Instituição</span>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card o-hidden border-0 shadow-lg my-3">
  <div class="card-body p-0">
    <div class="row">
      <div class="col-lg-12">
        <div class="p-3">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <!--<%= button_to new_escola_path, { method: 'get', class: 'd-none d-sm-inline-block btn btn-sm btn-primary shadow-sm' } do %>
                <i class="fas fa-plus-square" aria-hidden="true"> Nova escola</i>
            <% end %> -->

            <button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" id="btn_nova_escola">
              <i class="fas fa-plus-square" aria-hidden="true"> Nova instituição</i>
            </button>
          </div>
          <table class="table table-striped table-bordered table-hover table-escolas">
            <thead>
              <tr>
                <th>Instituição</th>
                <th>Endereço</th>
                <th>Número</th>
                <th>Bairro</th>
                <th>Cidade</th>
                <th>Responsável</th>
                <th>Telefone</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @escolas.each do |escola| %>
                <tr>
                  <td><%= escola.nome %></td>
                  <td><%= escola.endereco %></td>
                  <td><%= escola.numero %></td>
                  <td><%= escola.bairro %></td>
                  <td><%= escola.cidade %></td>
                  <td><%= escola.responsavel %></td>
                  <td><%= escola.telefone %></td>
                  <td><button class="btn btn-primary btn-sm" onclick="open_modal_edit_escola(<%= escola.id %>)">Editar</button></td>                  
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <%= render 'escolas/modal_new_escola' %>
  <%= render 'escolas/modal_edit_escola' %>
</div>
<br>

<script>
  $(document).ready(function() {
    
    $('.table-escolas').DataTable({
      pageLength: 10,
      responsive: true,
      dom: '<"html5buttons"B>lTfgitp',
      buttons: [
          {extend: 'excel', title: 'Empresas'},
          {extend: 'pdf', title: 'Empresas'}
      ],
      "ordering": true,
      "language": {
          "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json"
      }
    });
    
  });
</script>

app/views/escolas/new.html.erb
<h1>New Escola</h1>

<%= render 'form', escola: @escola %>

<%= link_to 'Back', escolas_path %>

app/views/escolas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @escola.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @escola.endereco %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @escola.numero %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @escola.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @escola.cidade %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @escola.responsavel %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @escola.telefone %>
</p>

<%= link_to 'Edit', edit_escola_path(@escola) %> |
<%= link_to 'Back', escolas_path %>